Fix labelling error (closes #11)
sugarlabs/wordcloud pull request #13
Opened 2022-08-02 18:10 UTC by sourabhaa

2022-08-04 07:27 UTC, srevinsaju requested changes

2022-08-04 07:27 UTC, srevinsaju commented on pytagcloud/lang/counter.py
> +    words = [x for x in re.findall(r'\w+', text, re.UNICODE)]
i think the list comprehension is redundant since we don't use `x.lower()` anymore. I think `words = re.findall(...)` would work the same.

2022-10-06 15:35 UTC, sourabhaa commented
@chimosky @quozl kindly review the PR

2022-10-06 19:18 UTC, quozl commented
I don't understand your change to line 29 of counter.py.  As this code is copied from pytagcloud, I don't understand why you haven't made the change to pytagcloud instead.  See https://github.com/atizo/PyTagCloud/blob/master/pytagcloud/lang/counter.py

2022-10-07 06:54 UTC, sourabhaa commented
> I don't understand your change to line 29 of counter.py.

@quozl , this line checks if the length of the word is more than 1 and if it's not a stop word in order to guess the word. So when a single character is entered in the first line to create a cloud, it throws error. When a single character is entered in any following lines, it is ignored.

2022-10-07 07:03 UTC, quozl commented
Thanks.  It is a problem in pytagcloud?

2022-10-07 07:08 UTC, sourabhaa commented
If I open a PR to pytagcloud repo, it won't reflect to wordcloud right?

2022-10-07 07:12 UTC, quozl commented
You're quite correct.  Let me explain.  Open source project maintenance is a social practice, and where we have copied code from other projects we have a social obligation to assist that other project.  The other project in this situation is pytagcloud.

Some time in the past we copied it.  We probably haven't kept our copy up to date.  When we find a problem that we can fix, we should look for the right way to fix it.  That usually involves merging all the "upstream" changes into our copy, testing each, looking for regressions, and we might end up with one of several results;

* updated local copy, everything works, nothing to do but commit the changes here,
* updated local copy, something fails, we may have to change our code,
* updated local copy, something fails, we discover a problem in the upstream code that we can fix, and we make a pull request to them and also keep our change here,
* nothing more recent than what we had works, so we stick with the old code and go our separate ways.

2022-10-07 07:25 UTC, sourabhaa commented
Thanks @quozl , there isn't any changes made to the file in pytagcloud since it was copied. Rather, we have updated it recently. I think it wouldn't be helpful to suggest our fix to their repo as the changes is done according our requirements.



(Could you also review the PR in[ Number rush](https://github.com/sugarlabs/numberrush-activity/pulls) activity?)

2022-10-07 08:20 UTC, quozl commented
https://github.com/atizo/PyTagCloud/blob/master/pytagcloud/lang/counter.py looks quite different; are there other upstream changes that should be taken into our activity?

Also, I don't understand why you removed lower().

2022-10-07 11:12 UTC, chimosky commented
> If I open a PR to pytagcloud repo, it won't reflect to wordcloud right?

No it won't but you can refer the PR here.

2022-10-07 11:24 UTC, sourabhaa commented
> https://github.com/atizo/PyTagCloud/blob/master/pytagcloud/lang/counter.py looks quite different; are there other upstream changes that should be taken into our activity?

Not really, the core logic remains the same, we have updated our copy with better handling of stop word check, porting to python 3 and other minor fixes. There isn't anything that we missed to take into our activity.

> Also, I don't understand why you removed lower().

I've done that to accept upper case character also. Till now, word cloud would be formed with lower case words irrespective of input.

2022-10-07 11:54 UTC, sourabhaa commented
> > If I open a PR to pytagcloud repo, it won't reflect to wordcloud right?
> 
> No it won't but you can refer the PR here.

Sorry, I didn't get you. How to refer? you mean opening the PR there and mentioning in this PR?

2022-10-07 11:54 UTC, chimosky commented
> > > If I open a PR to pytagcloud repo, it won't reflect to wordcloud right?
> > 
> > 
> > No it won't but you can refer the PR here.
> 
> Sorry, I didn't get you. How to refer? you mean opening the PR there and mentioning in this PR?

Yes.

2022-10-07 13:38 UTC, sourabhaa commented
> Yes.

Thanks, but I'm not sure if this patch is relevant to pytagcloud repo as it is updated as per the activities's requirement.

2022-10-07 17:31 UTC, quozl commented
It sounds like you want a word cloud to have uppercase letters.  That is unconventional, and an extra requirement above and beyond what pytagcloud provides?

You mention porting to Python 3 and other fixes.  Of the changes we have made to our copy of pytagcloud, are any of use to the pytagcloud project?  Their license does not require us to contribute back, but it's the sort of thing we do in open source development.

There's no need yet to link pull requests across the projects.  I'm open to any pytagcloud developers reading and talking here, but I don't think we need to attract their attention unless we have a problem with pytagcloud.

2022-10-08 12:13 UTC, sourabhaa commented
> It sounds like you want a word cloud to have uppercase letters. That is unconventional, and an extra requirement above and beyond what pytagcloud provides?

Yes @quozl , It is not provided by pytagcloud.

> You mention porting to Python 3 and other fixes. Of the changes we have made to our copy of pytagcloud, are any of use to the pytagcloud project?

Port to python3 might help pytagcloud. But since the our copy of code was modified for wordcloud activity from the initial commit, the ported code of our copy can't be merged to their repo. Hence none of our changes would be directly compatible with their repo. However, if it's modified as per their source code, it might be helpful for their repo.

2022-10-08 19:50 UTC, quozl commented
Thanks.  Also, the upstream repository has been inactive for many years, and there are an array of forks.  It may be difficult to engage.

2022-10-09 05:03 UTC, sourabhaa commented
@chimosky , kindly review :)

2022-10-10 12:22 UTC, chimosky commented
Reviewed and tested 891229b, works as expected. Thanks!

2022-10-10 12:22 UTC, merged